name: deployment
on:
    push:
        branches:
            - main
        paths-ignore:
            - ".github/workflows/*"
jobs:
    jo_1:
        runs-on: ubuntu-latest
        steps:
            - name: Get repository code
              uses: actions/checkout@v4
            - name: Cache
              uses: actions/cache@v4
              with:
                path: "~/.npm"
                key: "node-modules-${{ hashFiles('**/package-lock.json') }}"
            - name: Install depends
              run: npm install
            - name: runing tes
              run: npm run
    jo_2:
        runs-on: ubuntu-latest
        steps:
            - name: get repository code
              uses: actions/checkout@v4
            - name: Cache
              uses: actions/cache@v4
              with:
                path: "~/.npm"
                key: "node-modules-${{ hashFiles('**/package-lock.json') }}"
            - name: install depends
              run: npm install
            - name: lint test
              run: npm run lint
    jo_3:
        continue-on-error: true
        strategy:
            matrix:
                node-version: [14, 16]
                os: [ubuntu-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - name: get repository code
              uses: actions/checkout@v4
            - name: install npm
              uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-version }}
            - name: Cache
              uses: actions/cache@v4
              with:
                path: "~/.npm"
                key: "node-modules-${{ hashFiles('**/package-lock.json') }}"
            - name: install depends
              run: npm install
            - name: bild
              run: npm run build