name: deployment
on:
    push:
        branches:
            - main
        paths-ignore:
            - ".github/workflows/*"
jobs:
    jo_1:
        runs-on: ubuntu-latest
        steps:
            - name: Get repository code
              uses: actions/checkout@v4
            - name: Install depends
              run: npm install
            - name: runing tes
              run: npm run
    jo_2:
        runs-on: ubuntu-latest
        steps:
            - name: get repository code
              uses: actions/checkout@v4
            - name: install depends
              run: npm install
            - name: lint test
              run: npm run lint
    jo_3:
        runs-on: ubuntu-latest
        steps:
            - name: get repository code
              uses: actions/checkout@v4
            - name: install depends
              run: npm install
            - name: bild
              run: npm run build