name: test context
on:
    pull_request:
        branches:
            - main
        paths-ignore:
            - ".github/workflows/*"
jobs:
    jo_1:
        runs-on: ubuntu-latest
        steps:
            - name: context
              run: echo "${{ toJson(github.event) }}"